### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by icepy** [0x9simon/slaysybil#2]
suggestion: consider more complex exclusions to exclude normal users from this list, I'd be happy to discuss this with you if needed, thanks.

**Comment by 0x9simon** [comment]
I agree with you on the exlucsion of normal users. First of all, the projct is built for fulfil the task of the Gitcoin Sybil Prevention Hackathon. It is far from a Sybil Prevention System than can be used in reality. Secondly, false positive is not a major issur in this comepetition. The host was concerned more about the ideas and signals. Third, our team namely the Trusta Labs are building the product that can be really used by projects for preventing sybils. If you are interested in the topic (not from a sybil perspective), please join us :-)

**Comment by 0x9simon** [comment]
I reply in github.&nbsp;


如果你也对如何hunter女巫有兴趣，并且有数据的技能，欢迎加入！




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Send time:&nbsp;Saturday, Nov 26, 2022 11:27 PM
***@***.***&gt;; 
***@***.***&gt;; 
Subject: &nbsp;[0x9simon/slaysybil] feedback (Issue #2)





 
i really want to express: your research has a lot of loopholes, and some normal addresses are marked, why do you say that?
  
my most used addresses are in your sybil attack list
  
because for addresses with a large amount of funds, for the sake of safety, the funds will be dispersed to different addresses to use the project, each project configures an address separately, such as: trading NFT configures an address, DeFi mining configures an address, high-value games configures an address, and even a game configures an address.
 
these addresses are all attributed to Sybil attacks, which is obviously not a reasonable choice and creates a barrier for normal users. the deeper problem is that this is my personal brand address, which has a bad impact on my reputation in the community.
 
suggestion: consider more complex exclusions to exclude normal users from this list, I'd be happy to discuss this with you if needed, thanks.
